get_phylomarkers_fun_lib v2024-04-02: renamed mispelled SRHtests

diff --git a/lib/get_phylomarkers_fun_lib b/lib/get_phylomarkers_fun_lib
--- a/lib/get_phylomarkers_fun_lib
+++ b/lib/get_phylomarkers_fun_lib
@@ -1,4 +1,4 @@
-#: VERSION: 2024-03-30
+#: VERSION: 2024-04-02
 #: LIBRARY: get_phylomarkers_fun_lib
 #     * functions called by run_get_phylomarkers_pipeline.sh
 #     * part of the GET_PHYLOMARKERS software package
@@ -887,7 +887,7 @@ function msg()
 }
 #-----------------------------------------------------------------------------------------
 
-parse_SRM_tests() {
+parse_SRH_tests() {
    # This function parses tables generated by the maximal matched-pairs tests of homogeneity 
    #   to asses the SRH model violations.
    # SRH = Stationarity, Reversibility, and Homogeneity assumptions made by standard substitutio models
@@ -928,26 +928,26 @@ parse_SRM_tests() {
 
    # Move failed symtest FASTA files (codon and faaln to their directory
    if ((no_alns_failing_SRHtests >= 1)) && [[ -s SRHtests_failed.tsv ]]; then
-      mkdir SMRtests_failed || { msg "ERROR: could not mkdir SMRtests_failed/" ERROR RED && exit 1 ; }
+      mkdir SRHtests_failed || { msg "ERROR: could not mkdir SRHtests_failed/" ERROR RED && exit 1 ; }
       for f in $(awk 'BEGIN{FS="\t"}NR > 1{print $1}' SRHtests_failed.tsv); do
           fasta_base="${f/_cdnAln.*/}" 
-          mv "${fasta_base}"* SMRtests_failed
+          mv "${fasta_base}"* SRHtests_failed
       done
    fi
 
    # cleanup
-   (( DEBUG > 0 )) && msg "DEGUB: creating SMRtests_failed.tgz and removing SMRtests_failed/" DEBUG NC
-   [ -d SMRtests_failed ] && tar -czf SMRtests_failed.tgz SMRtests_failed
-   [ -s SMRtests_failed.tgz ] && rm -rf SMRtests_failed
+   (( DEBUG > 0 )) && msg "DEGUB: creating SRHtests_failed.tgz and removing SRHtests_failed/" DEBUG NC
+   [ -d SRHtests_failed ] && tar -czf SRHtests_failed.tgz SRHtests_failed
+   [ -s SRHtests_failed.tgz ] && rm -rf SRHtests_failed
 
-   (( DEBUG > 0 )) && msg "DEGUB: creating SMRtests_OK/ and SMRtests_OK.tgz/" DEBUG NC
-   mkdir SMRtests_OK || { msg "ERROR: could not mkdir SMRtests_OK/" ERROR RED && exit 1 ; }
-   if [ -d SMRtests_OK ]
+   (( DEBUG > 0 )) && msg "DEGUB: creating SRHtests_OK/ and SRHtests_OK.tgz/" DEBUG NC
+   mkdir SRHtests_OK || { msg "ERROR: could not mkdir SRHtests_OK/" ERROR RED && exit 1 ; }
+   if [ -d SRHtests_OK ]
    then
-      mv ./*cdnAln.fasta.log SMRtests_OK
-      mv ./*fasta.symtest.csv SMRtests_OK
-      tar -czf SMRtests_OK.tgz SMRtests_OK || { msg "ERROR: could not make tgz SMRtests_OK.tgz" ERROR RED && exit 1 ; }
-      [ -s SMRtests_OK.tgz ] && rm -rf SMRtests_OK
+      mv ./*cdnAln.fasta.log SRHtests_OK
+      mv ./*fasta.symtest.csv SRHtests_OK
+      tar -czf SRHtests_OK.tgz SRHtests_OK || { msg "ERROR: could not make tgz SRHtests_OK.tgz" ERROR RED && exit 1 ; }
+      [ -s SRHtests_OK.tgz ] && rm -rf SRHtests_OK
    fi
    
    (( DEBUG > 0 )) && msg " <= exiting ${FUNCNAME[0]} ..." DEBUG NC
