get_phylomarkers_fun_lib v2024-03-28
 - added function parse_SRM_tests, to generate tabular format of the
   maximal matched-pairs tests, to asses SRH assumptions.

diff --git a/lib/get_phylomarkers_fun_lib b/lib/get_phylomarkers_fun_lib
--- a/lib/get_phylomarkers_fun_lib
+++ b/lib/get_phylomarkers_fun_lib
@@ -33,16 +33,16 @@
 
 function get_script_PID()
 {
-    #(( DEBUG > 0 )) && msg " => working in ${FUNCNAME[0]}  ..." DEBUG NC
-    # returns the PID of the script, run by USER
-    local prog user
-    user=$1
-    prog=${2%.*} # remove the script's .extension_name
-    #proc_ID=$(ps -eaf|grep "$prog"|grep -v grep|grep '-'|grep $USER|awk '{print $2}')
-    #proc_ID=$(ps aux|grep "$prog"|grep -v grep|grep '-'|grep $USER|awk '{print $2}')
-    proc_ID=$(pgrep -u "$user" "$prog")
-    echo "$proc_ID"
-    #(( DEBUG > 0 )) && msg "$progname PID is: $proc_ID" DEBUG NC
+   #(( DEBUG > 0 )) && msg " => working in ${FUNCNAME[0]}  ..." DEBUG NC
+   # returns the PID of the script, run by USER
+   local prog user
+   user=$1
+   prog=${2%.*} # remove the script's .extension_name
+   #proc_ID=$(ps -eaf|grep "$prog"|grep -v grep|grep '-'|grep $USER|awk '{print $2}')
+   #proc_ID=$(ps aux|grep "$prog"|grep -v grep|grep '-'|grep $USER|awk '{print $2}')
+   proc_ID=$(pgrep -u "$user" "$prog")
+   echo "$proc_ID"
+   #(( DEBUG > 0 )) && msg "$progname PID is: $proc_ID" DEBUG NC
 }
 #-----------------------------------------------------------------------------------------
 
@@ -843,7 +843,6 @@ function check_IQT_PROT_models
    return 0
 }
 #-----------------------------------------------------------------------------------------
-
 function msg()
 {
     #(( DEBUG > 0 )) && msg " => working in ${FUNCNAME[0]}  ..." DEBUG NC
@@ -878,3 +877,66 @@ function msg()
    return 0
 }
 #-----------------------------------------------------------------------------------------
+parse_SRM_tests() {
+   # This function parses tables generated by the maximal matched-pairs tests of homogeneity 
+   #   to asses the SRH model violations.
+   # SRH = Stationarity, Reversibility, and Homogeneity assumptions made by standard substitutio models
+   # The test is implemented in IQ-Tree, as published by Naser-Khdour et al. (2019) in GBE 11(12)3341-3352.
+   (( DEBUG > 0 )) && msg " => working in ${FUNCNAME[0]}  ..." DEBUG NC
+   (( DEBUG > 0 )) && caller 0
+   for f in *.csv
+   do 
+      fasta="${f/.symtest.csv/}"
+      perc_failed_comp_ChiSq=$(grep TOTAL "${fasta}".log | sed 's/\*\*\*\*  //' | awk '{print $2}')
+      num_failed_comp_ChiSq=$(grep TOTAL "${fasta}".log | sed 's/\*\*\*\*  //' | awk '{print $3}')
+      SymPval=$(grep Noname "$f" | awk 'BEGIN{FS=","}{print $4}')
+      MarPval=$(grep Noname "$f" | awk 'BEGIN{FS=","}{print $7}')
+      IntPval=$(grep Noname "$f" | awk 'BEGIN{FS=","}{print $10}')
+    
+      # print parsed output line
+      echo -e "$fasta\t$SymPval\t$MarPval\t$IntPval\t$perc_failed_comp_ChiSq\t$num_failed_comp_ChiSq"     
+   done > parsed_SRHtests.tsv   
+   check_output parsed_SRHtests.tsv "$parent_PID"
+
+   # identify the alignments passing the SRHtests
+   awk 'BEGIN{FS=OFS="\t"; print "alignment\tSymPval\tMarPval\tIntPval\tperc_failed_comp\tnum_failed_comp"}
+     $2 > 0.05 && $3 > 0.05 && $4 > 0.05' parsed_SRHtests.tsv > SRHtests_passed.tsv
+   check_output SRHtests_passed.tsv "$parent_PID"
+
+   # identify alignments failing the symtests
+   awk 'BEGIN{FS=OFS="\t"; print "alignment\tSymPval\tMarPval\tIntPval\tperc_failed_comp\tnum_failed_comp"}
+      $2 <= 0.05 || $3 <= 0.05 || $4 <= 0.05' parsed_SRHtests.tsv > SRHtests_failed.tsv
+   check_output SRHtests_failed.tsv "$parent_PID"
+
+   no_alns_failing_SRHtests=$(cat SRHtests_failed.tsv | wc -l)
+   no_alns_failing_SRHtests=$((no_alns_failing_SRHtests - 1)) # remove header
+
+   msg ">>> $no_alns_failing_SRHtests codon alignments failed the SRH tests" PROGR GREEN
+
+   # Move failed symtest to their directory
+   if ((no_alns_failing_SRHtests >= 1)); then
+      mkdir SMRtests_failed || { msg "ERROR: could not mkdir SMRtests_failed/" ERROR RED && exit 1 ; }
+      for f in $(awk 'NR > 1{print $1}' SRHtests_failed.tsv | sed 's/\.symtest\.csv//'); do 
+         mv "$f" SMRtests_failed
+      done
+   fi
+
+   # cleanup
+   (( DEBUG > 0 )) && msg "DEGUB: creating SMRtests_failed.tgz and removing SMRtests_failed/" DEBUG NC
+   [ -d SMRtests_failed ] && tar -czf SMRtests_failed.tgz SMRtests_failed
+   [ -s SMRtests_failed.tgz ] && rm -rf SMRtests_failed
+
+   (( DEBUG > 0 )) && msg "DEGUB: creating SMRtests_OK/ and SMRtests_OK.tgz/" DEBUG NC
+   mkdir SMRtests_OK || { msg "ERROR: could not mkdir SMRtests_OK/" ERROR RED && exit 1 ; }
+   if [ -d SMRtests_OK ]
+   then
+      mv ./*cdnAln.fasta.log SMRtests_OK
+      mv ./*fasta.symtest.csv SMRtests_OK
+      tar -czf SMRtests_OK.tgz SMRtests_OK || { msg "ERROR: could not make tgz SMRtests_OK.tgz" ERROR RED && exit 1 ; }
+      [ -s SMRtests_OK.tgz ] && rm -rf SMRtests_OK
+   fi
+   
+   (( DEBUG > 0 )) && msg " <= exiting ${FUNCNAME[0]} ..." DEBUG NC
+
+   return 0
+}
